version: '3'
services:
  frontend:
    image: gab020/vite-react
# Using network_mode to fix Connection reset by peer: https://stackoverflow.com/a/57774458
# Verify the port where vite is running with the command: sudo docker logs vite-react
# Local:   http://localhost:3000/
    container_name: vite-react
#    network_mode: host
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    image: gab020/flaskimg
    container_name: flask
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: mongo
    container_name: mongodb
    ports:
      - "27017"
    volumes:
      - ~/mongodb_data:/data/db
